name: CI
on:
  pull_request:
    paths-ignore:
    - docs/**
    - README.md
  push:
    branches:
    - main

jobs:
  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - '3.9'
        - '3.11'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install FFTW (macOS)
      if: runner.os == 'macOS'
      run: brew install fftw

    - name: Setup package
      env:
        C_INCLUDE_PATH: ${{ if eq(runner.os, 'macOS') }}{/opt/homebrew/include}{:else}{/usr/include}{:endif}
        LIBRARY_PATH: ${{ if eq(runner.os, 'macOS') }}{/opt/homebrew/lib}{:else}{/usr/lib}{:endif}
        PKG_CONFIG_PATH: ${{ if eq(runner.os, 'macOS') }}{/opt/homebrew/lib/pkgconfig}{:else}{/usr/lib/pkgconfig}{:endif}
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"
    - name: Run tests
      run: |
        pytest --color=yes
