name: CI
on:
  pull_request:
    paths-ignore:
    - docs/**
    - README.md
  push:
    branches:
    - main

jobs:
  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - '3.8'
        - '3.11'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install FFTW
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libfftw3-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install fftw
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install fftw
        fi
    - name: Setup package
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"
    - name: Run tests
      run: |
        pytest --color=yes
